### PR TITLE
Fix duplicate application name

### LINKED ISSUE #625: Bug: the provider seems to send a duplicate application name
The Terraform provider seems to send a duplicate application name:

```
terraform-provider-materialize v0.8.5 terraform-provider-materialize v0.8.5
```

The problem seems to be in the `NewDBClient` method:

https://github.com/MaterializeInc/terraform-provider-materialize/blob/a74af7470cdc219191d2edf749df511293484c43/pkg/provider/provider.go#L217

https://github.com/MaterializeInc/terraform-provider-materialize/blob/a74af7470cdc219191d2edf749df511293484c43/pkg/clients/db_client.go#L18

### PR DESCRIPTION
**Pull request by bobbyiliev**
Fixes #625

### CODE REVIEW

File: pkg/clients/db_client.go [hunk 1]
```diff
@@ -15,9 +15,11 @@ type DBClient struct {
 func NewDBClient(host, user, password string, port int, database, application_name_suffix, version, sslmode string) (*DBClient, diag.Diagnostics) {
 	var diags diag.Diagnostics
 
-	application_name := fmt.Sprintf("terraform-provider-materialize v%s", version)
+	var application_name string
 	if application_name_suffix != "" {
-		application_name += " " + application_name_suffix
+		application_name = application_name_suffix
```
Comment (RobinClowers) [inline pkg/clients/db_client.go:20]: It seems confusing to call this _suffix if it's actually the full application name?

**Review by RobinClowers — APPROVED** [review]

File: pkg/clients/db_client.go (hunk 1 above)
Comment (bobbyiliev) [reply pkg/clients/db_client.go]: Good point! I changed this a bit as it indeed did not make sense to have it this way
